add_rules("mode.debug", "mode.release")

add_repositories("levimc-repo https://github.com/LiteLDev/xmake-repo.git")

add_requires("aklomp-base64 0.5.2")
add_requires("boost 1.86.0")
add_requires("moodycamelconqueue 1.0.4")
add_requires("cpptrace 1.0.4")
add_requires("date 3.0.4")
add_requires("entt v3.15.0")
add_requires("expected-lite v0.8.0")
add_requires("fmt 11.2.0")
add_requires("glm 1.0.1")
add_requires("magic_enum v0.9.7")
add_requires("gsl v4.2.0")
add_requires("pybind11 3.0.1")
add_requires("replxx 2021.11.25")
add_requires("toml++ v3.3.0")
add_requires("zstr v1.0.7")

add_requires("microsoft-detours 9764cebcb1a75940e68fa83d6730ffaf0f669401")
add_requires("funchook v1.1.3")
add_requires("mimalloc v2.1.7")

add_requires("levilamina 1.9.8")
add_requires("levibuildscript")

local get_version = function(os)
    local tags = os.iorun("git describe --tags --long")
    local tag, num_commits, commit_hash = tags:match("v?(%S+)-(%d+)-g([a-f0-9]+)")
    if tonumber(num_commits) > 0 then
        local major, minor, patch = tag:match("(%d+)%.(%d+)%.(%d+)")
        if major and minor and patch then
            tag = string.format("%s.%s.%d", major, minor, tonumber(patch) + 1)
        end
        tag = tag..".dev"..num_commits
    end
    return tag
end

set_project("endstone")
set_languages("c++20")
set_runtimes("MD")

rule("patch_vulnerability_fixes")
    on_load(function (target)
        -- Patch symbols.toml and vulnerability fixes
        os.cd("$(projectdir)/endstone")
        os.runv("git", {"restore", "."})
        os.runv("git", {"apply", "../patches/Disable_vulnerability_fixes_already_included_in_LeviLamina.patch"})
        os.cd("$(projectdir)")
    end)

rule("generate_symbols")
    on_load(function (target)
        local toml = import("scripts.toml")
        local symbols = toml.parse(io.readfile( "endstone/src/bedrock/symbol_generator/symbols.toml"))[target:plat()]
        local count = 0
        for _ in pairs(symbols) do count = count + 1 end
        local file = assert(io.open("$(builddir)/generated/bedrock_symbols.generated.h", "w"), "Failed to open symbol file")
        file:write("#pragma once\n\n")
        file:write("// clang-format off\n")
        file:write("#include <array>\n")
        file:write("#include <string_view>\n\n")
        file:write("static constexpr std::array<std::pair<std::string_view, std::size_t>, ")
        file:write(count)
        file:write("> symbols = {{\n")
        for k, v in pairs(symbols) do
            file:print("    { \"%s\", %d },", k, v)
        end
        file:write("}};\n")
        file:write("// clang-format on\n")
        file:close()
    end)

target("endstone")
    set_kind("headeronly")
    set_languages("c++20")
    add_includedirs("endstone/include", {interface = true})
    add_packages("fmt", "expected-lite", {interface = true})

target("bedrock")
    add_rules("patch_vulnerability_fixes", "generate_symbols")
    set_kind("object")
    set_languages("c++20")
    add_includedirs("endstone/src", "$(builddir)/generated", {public = true})
    add_files("endstone/src/bedrock/**.cpp")
    remove_files("endstone/src/bedrock/symbol_generator/**.cpp")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/O2 /DNDEBUG /Gy")
    add_defines("ENTT_SPARSE_PAGE=2048", "ENTT_PACKED_PAGE=128", "ENTT_NO_MIXIN", {public = true})
    add_deps("endstone", {public = true})
    add_packages("aklomp-base64", "boost", "fmt", "entt", "glm", "magic_enum", "gsl", "expected-lite", {public = true})

target("endstone_python")
    set_basename("_python")
    add_rules("python.module")
    add_files("endstone/src/endstone/python/**.cpp")
    add_files("src/levistone/python/**.cpp")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/utf-8 /O2 /DNDEBUG /Gy")
    add_defines("PYBIND11_DETAILED_ERROR_MESSAGES")
    add_deps("endstone")
    add_packages("mimalloc", "pybind11", "microsoft-detours")
    set_symbols("debug")
    after_build(function (target)
        os.cp("endstone/endstone", "bin/EndstoneRuntime/")
        os.cp(target:targetfile(), "bin/EndstoneRuntime/endstone/")
    end)

target("endstone_core")
    set_kind("static")
    set_languages("c++20")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/O2 /DNDEBUG /Gy")
    add_defines("PYBIND11_DETAILED_ERROR_MESSAGES")
    add_files("endstone/src/endstone/core/**.cpp")
    add_files("src/levistone/core/**.cpp")
    remove_files("endstone/src/endstone/core/command/defaults/version_command.cpp")
    remove_files("endstone/src/endstone/core/devtools/**.cpp")
    remove_files("endstone/src/endstone/core/spdlog/**.cpp")
    remove_files("endstone/src/endstone/core/crash_handler.cpp")
    remove_files("endstone/src/endstone/core/logger_factory.cpp")
    remove_files("endstone/src/endstone/core/signal_handler.cpp")
    add_deps("bedrock")
    add_packages("moodycamelconqueue", "cpptrace", "date", "replxx", "pybind11", "toml++", "zstr", "levilamina", {public = true})
    on_load(function (target)
        target:add("defines", "ENDSTONE_VERSION=\""..get_version(os).."\"")
    end)

target("endstone_runtime")
    set_kind("shared")
    add_includedirs("src/")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /EXPORT:DllMain,@1,NONAME")
    add_cxflags("/utf-8 /O2 /DNDEBUG /Gy")
    add_defines("_CRT_SECURE_NO_WARNINGS")
    add_files("src/levistone/memory_operators.cpp")
    add_files("endstone/src/endstone/runtime/windows.cpp")
    add_files("endstone/src/endstone/runtime/vtable_hook.cpp")
    add_files("endstone/src/endstone/runtime/bedrock_hooks/**.cpp")
    add_files("src/levistone/runtime/**.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/dedicated_server.cpp")
    add_deps("endstone_core")
    add_packages("funchook")
    add_links("dbghelp", "ws2_32","Psapi")
    set_symbols("debug")
    on_load(function (target)
        target:add("rules", "@levibuildscript/modpacker", {
            modName = "EndstoneRuntime",
            modVersion = get_version(os)
        })
    end)
