add_rules("mode.debug", "mode.release")

add_repositories("levimc-repo https://github.com/LiteLDev/xmake-repo.git")
add_repositories("local-repo repository")

add_requires("aklomp-base64 0.5.2", {configs = {cxflags = "-clang:-Wno-error"}})
add_requires("boost 1.91.0-1")
add_requires("moodycamelconqueue 1.0.4")
add_requires("cpptrace 1.0.4")
add_requires("date 3.0.4")
add_requires("entt v3.15.0")
add_requires("expected-lite v0.9.0")
add_requires("fmt 12.1.0")
add_requires("glm 1.0.3")
add_requires("magic_enum v0.9.7")
add_requires("gsl v4.2.2")
add_requires("pybind11 3.0.1")
-- clang-cl disables C++ exceptions by default, and xmake's
-- package snippet check only injects /EHsc for the "cl" tool, so compile checks
-- of packages using try/catch (e.g. pybind11) fail without this.
add_requireconfs("pybind11", {configs = {cxflags = "/EHsc"}})
add_requires("replxx 2021.11.25")
add_requires("toml++ v3.3.0")
add_requires("zstr v1.0.7")
add_requires("demangler")
add_requires("raknet")

add_requires("microsoft-detours a1dd93fddfbba5ad07992edbaf4a296dcfca8d6f")
add_requires("mimalloc v3.5.0")

add_requires("levilamina 26.40.*")
add_requires("levibuildscript")

set_project("endstone")
set_languages("c++20")
set_runtimes("MD")
set_toolchains("clang-cl")

target("endstone")
    set_kind("headeronly")
    set_languages("c++20")
    add_includedirs("endstone/include", "$(builddir)/generated", {interface = true})
    add_packages("fmt", "expected-lite", {interface = true})
    set_configdir("$(builddir)/generated/endstone")
    add_configfiles("endstone/include/endstone/version.h.in", {pattern = "@(.-)@"})
    on_load(function (target)
        local tags = os.iorun("git describe --tags --long")
        local tag, num_commits, commit_hash = tags:match("v?(%S+)-(%d+)-g([a-f0-9]+)")
        local major, minor, patch = tag:match("(%d+)%.(%d+)%.(%d+)")
        target:set("configvar", "PROJECT_VERSION_MAJOR", major)
        target:set("configvar", "PROJECT_VERSION_MINOR", minor)
        target:set("configvar", "PROJECT_VERSION_PATCH", patch)
        if tonumber(num_commits) > 0 then
            tag = string.format("%s.%s.%d.dev%s", major, minor, tonumber(patch) + 1, num_commits)
        end
        target:set("configvar", "ENDSTONE_VERSION_FULL", tag)
    end)

target("bedrock")
    set_kind("object")
    set_languages("c++20")
    add_includedirs("src", "endstone/src", {public = true})
    add_files("endstone/src/bedrock/**.cpp")
    add_files("src/bedrock/**.cpp")
    remove_files("endstone/src/bedrock/server/commands/command_registry.cpp")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/O2 /DNDEBUG /Gy")
    add_defines("ENTT_SPARSE_PAGE=2048", "ENTT_PACKED_PAGE=128", "ENTT_NO_MIXIN", {public = true})
    add_deps("endstone")
    add_packages("aklomp-base64", "boost", "fmt", "entt", "glm", "magic_enum", "gsl", "expected-lite", "raknet", {public = true})

target("endstone_python")
    set_basename("_python")
    add_includedirs("endstone/src")
    add_rules("python.module")
    add_files("endstone/src/endstone/python/**.cpp")
    add_files("src/endstone/python/**.cpp")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/utf-8 /O2 /DNDEBUG /Gy")
    add_defines("PYBIND11_DETAILED_ERROR_MESSAGES")
    add_deps("endstone")
    add_packages("mimalloc", "pybind11", "microsoft-detours")
    set_symbols("debug")
    after_build(function (target)
        os.cp("endstone/endstone", "bin/EndstoneRuntime/")
        os.cp(target:targetfile(), "bin/EndstoneRuntime/endstone/")
    end)

target("endstone_core")
    set_kind("static")
    set_languages("c++20")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/O2 /DNDEBUG /Gy")
    add_defines("PYBIND11_DETAILED_ERROR_MESSAGES")
    add_files("endstone/src/endstone/core/**.cpp")
    add_files("src/endstone/core/**.cpp")
    remove_files("endstone/src/endstone/core/command/defaults/version_command.cpp")
    remove_files("endstone/src/endstone/core/devtools/**.cpp")
    remove_files("endstone/src/endstone/core/spdlog/**.cpp")
    remove_files("endstone/src/endstone/core/crash_handler.cpp")
    remove_files("endstone/src/endstone/core/logger_factory.cpp")
    remove_files("endstone/src/endstone/core/signal_handler.cpp")
    add_deps("bedrock")
    add_packages("moodycamelconqueue", "cpptrace", "date", "replxx", "pybind11", "toml++", "zstr", "levilamina", {public = true})

target("endstone_runtime")
    set_kind("shared")
    add_includedirs("src")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /EXPORT:DllMain,@1,NONAME")
    add_cxflags("/utf-8 /O2 /DNDEBUG /Gy")
    add_defines("_CRT_SECURE_NO_WARNINGS")
    add_files("src/endstone/memory_operators.cpp")
    add_files("endstone/src/endstone/runtime/windows.cpp")
    add_files("endstone/src/endstone/runtime/bedrock_hooks/**.cpp")
    add_files("src/endstone/runtime/**.cpp")
    remove_files("endstone/src/endstone/runtime/vtable_hook.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/dedicated_server.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/server_network_handler.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/item.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/packet.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/batched_network_peer.cpp")
    add_deps("endstone_core")
    add_packages("demangler")
    add_links("dbghelp", "ws2_32","Psapi")
    set_symbols("debug")
    on_load(function (target)
        target:add("rules", "@levibuildscript/modpacker", {
            modName = "EndstoneRuntime",
        })
    end)
