add_rules("mode.debug", "mode.release")

add_repositories("levimc-repo https://github.com/LiteLDev/xmake-repo.git")

add_requires("aklomp-base64 0.5.2")
add_requires("boost 1.84.0")
add_requires("moodycamelconqueue 1.0.4")
add_requires("cpptrace 1.0.4")
add_requires("date 3.0.4")
add_requires("entt v3.15.0")
add_requires("expected-lite v0.8.0")
add_requires("fmt 11.2.0")
add_requires("glm 1.0.1")
add_requires("magic_enum v0.9.7")
add_requires("gsl v4.2.0")
add_requires("pybind11 3.0.1")
add_requires("replxx 2021.11.25")
add_requires("toml++ v3.3.0")
add_requires("zstr v1.0.7")
add_requires("demangler")

add_requires("microsoft-detours 9764cebcb1a75940e68fa83d6730ffaf0f669401")
add_requires("mimalloc v2.1.7")

add_requires("levilamina 26.10.*")
add_requires("levibuildscript")

local get_version = function(os)
    local tags = os.iorun("git describe --tags --long")
    local tag, num_commits, commit_hash = tags:match("v?(%S+)-(%d+)-g([a-f0-9]+)")
    if tonumber(num_commits) > 0 then
        local major, minor, patch = tag:match("(%d+)%.(%d+)%.(%d+)")
        if major and minor and patch then
            tag = string.format("%s.%s.%d", major, minor, tonumber(patch) + 1)
        end
        tag = tag..".dev"..num_commits
    end
    return tag
end

set_project("endstone")
set_languages("c++20")
set_runtimes("MD")

target("endstone")
    set_kind("headeronly")
    set_languages("c++20")
    add_includedirs("endstone/include", {interface = true})
    add_packages("fmt", "expected-lite", {interface = true})

target("bedrock")
    set_kind("object")
    set_languages("c++20")
    add_includedirs("src", "endstone/src", {public = true})
    add_files("endstone/src/bedrock/**.cpp")
    remove_files("endstone/src/bedrock/symbol_generator/**.cpp")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/O2 /DNDEBUG /Gy")
    add_defines("ENTT_SPARSE_PAGE=2048", "ENTT_PACKED_PAGE=128", "ENTT_NO_MIXIN", {public = true})
    add_deps("endstone")
    add_packages("aklomp-base64", "boost", "fmt", "entt", "glm", "magic_enum", "gsl", "expected-lite", {public = true})

target("endstone_python")
    set_basename("_python")
    add_rules("python.module")
    add_files("endstone/src/endstone/python/**.cpp")
    add_files("src/endstone/python/**.cpp")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/utf-8 /O2 /DNDEBUG /Gy")
    add_defines("PYBIND11_DETAILED_ERROR_MESSAGES")
    add_deps("endstone")
    add_packages("mimalloc", "pybind11", "microsoft-detours")
    set_symbols("debug")
    after_build(function (target)
        os.cp("endstone/endstone", "bin/EndstoneRuntime/")
        os.cp(target:targetfile(), "bin/EndstoneRuntime/endstone/")
    end)

target("endstone_core")
    set_kind("static")
    set_languages("c++20")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
    add_cxflags("/O2 /DNDEBUG /Gy")
    add_defines("PYBIND11_DETAILED_ERROR_MESSAGES")
    add_files("endstone/src/endstone/core/**.cpp")
    add_files("src/endstone/core/**.cpp")
    remove_files("endstone/src/endstone/core/command/defaults/version_command.cpp")
    remove_files("endstone/src/endstone/core/devtools/**.cpp")
    remove_files("endstone/src/endstone/core/spdlog/**.cpp")
    remove_files("endstone/src/endstone/core/crash_handler.cpp")
    remove_files("endstone/src/endstone/core/logger_factory.cpp")
    remove_files("endstone/src/endstone/core/signal_handler.cpp")
    add_deps("bedrock")
    add_packages("moodycamelconqueue", "cpptrace", "date", "replxx", "pybind11", "toml++", "zstr", "levilamina", {public = true})
    on_load(function (target)
        target:add("defines", "ENDSTONE_VERSION=\""..get_version(os).."\"")
    end)

target("endstone_runtime")
    set_kind("shared")
    add_includedirs("src")
    add_ldflags("/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /EXPORT:DllMain,@1,NONAME")
    add_cxflags("/utf-8 /O2 /DNDEBUG /Gy")
    add_defines("_CRT_SECURE_NO_WARNINGS")
    add_files("src/endstone/memory_operators.cpp")
    add_files("endstone/src/endstone/runtime/windows.cpp")
    add_files("endstone/src/endstone/runtime/bedrock_hooks/**.cpp")
    add_files("src/endstone/runtime/**.cpp")
    remove_files("endstone/src/endstone/runtime/vtable_hook.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/dedicated_server.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/server_network_handler.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/item.cpp")
    remove_files("endstone/src/endstone/runtime/bedrock_hooks/certificate.cpp")
    add_deps("endstone_core")
    add_packages("demangler")
    add_links("dbghelp", "ws2_32","Psapi")
    set_symbols("debug")
    on_load(function (target)
        target:add("rules", "@levibuildscript/modpacker", {
            modName = "EndstoneRuntime",
        })
    end)
