name: Wheel

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

permissions: read-all

jobs:
  build_wheels:
    name: Build Wheel (${{ matrix.python-tag }}-${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-tag: ["cp39", "cp310", "cp311", "cp312", "cp313"]
        include:
          - os: windows-latest
            platform: win_amd64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - uses: matbour/setup-sentry-cli@v1
        with:
          token: ${{ SECRETS.SENTRY_TOKEN }}
          organization: ${{ SECRETS.SENTRY_ORG }}
          project: ${{ SECRETS.SENTRY_PROJECT }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD: ${{ matrix.python-tag }}-${{ matrix.platform }}
          CIBW_BUILD_VERBOSITY: 1

      - run: |
          sentry-cli debug-files upload --include-sources bin/

      - uses: actions/upload-artifact@v4
        with:
          name: levistone-wheels-${{ matrix.python-tag }}-${{ matrix.platform }}
          path: ./wheelhouse/*.whl

  pypi-publish:
    name: Upload Wheels to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: levistone-wheels-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1